### ISSUE TITLE
Feature modification

### ISSUE THREAD

**Issue by Raushantechfest** [IamAbhiKaushik/cobid_frontend#11]
![Screenshot_2020-04-26-22-34-07-663_com android chrome](https://user-images.githubusercontent.com/30129252/80314266-1adf8f80-880e-11ea-8c08-379dd9d66ec7.jpg)
Make sure every option is visible or add a scroll

**Comment by psg0796** [comment]
fixed in commit id --> f28f2a6a537e0e9c522b44c158398b81de94c785
