### ISSUE TITLE
Dynamic total bids

### ISSUE THREAD

**Issue by Raushantechfest** [IamAbhiKaushik/cobid_frontend#13]
Total bids is not dynamic
![Screenshot_2020-04-26-23-53-35-791_com android chrome](https://user-images.githubusercontent.com/30129252/80316113-8aa74780-8819-11ea-8926-b5083dd243c8.jpg)

**Comment by psg0796** [comment]
@Raushantechfest what is meant by not dynamic? Should it be dynamic like when any person bets on it the count should increase???

**Comment by psg0796** [comment]
@Raushantechfest , if this is supposed to be something like a live tracker for the number of persons betting on the questions then it's hard as of now to implement, this will include some network overheads and may make page slow. But if there is some interval after which this needs to be updated then can do this.

**Comment by Raushantechfest** [comment]
> @Raushantechfest what is meant by not dynamic? Should it be dynamic like when any person bets on it the count should increase???

Yes. it should increase or decrease

**Comment by Raushantechfest** [comment]
> @Raushantechfest , if this is supposed to be something like a live tracker for the number of persons betting on the questions then it's hard as of now to implement, this will include some network overheads and may make page slow. But if there is some interval after which this needs to be updated then can do this.

@IamAbhiKaushik Your views on this?

**Comment by IamAbhiKaushik** [comment]
We are not implementing this. Sorry for late response.
