### ISSUE TITLE
Result publish and coin reset

### ISSUE THREAD

**Issue by Raushantechfest** [IamAbhiKaushik/cobid_frontend#15]
Coins should reset and results must be published at the end of deadline

**Comment by psg0796** [comment]
For this we need a results section for a person, so that he can view whether he won or lost and how many coins he lost and gained.

**Comment by Raushantechfest** [comment]
> For this we need a results section for a person, so that he can view whether he won or lost and how many coins he lost and gained.

@IamAbhiKaushik You guys discuss on the console part for this
