### ISSUE TITLE
Wording change for Avg Bids

### ISSUE THREAD

**Issue by Raushantechfest** [IamAbhiKaushik/cobid_frontend#18]
Change Avg. Bids to - "Avg. Bid Size"

**Comment by psg0796** [comment]
@Raushantechfest Size!!!!!!!!!!!!!!! shouldn't it be something like Avg. Bid Amount or Avg Bid Coins or just leave it to Avg Bid.

@IamAbhiKaushik

**Comment by Raushantechfest** [comment]
Any of the 3 works for me.. coz it brings clarity in understanding. When people are looking at it for the first time then they might not get what we mean.. So, add that.

**Comment by psg0796** [comment]
update done in commit id --> d7980d72e60537ee0d4eb509b8346c8500238ccf
