### ISSUE TITLE
Coins Summary height reduction

### ISSUE THREAD

**Issue by Raushantechfest** [IamAbhiKaushik/cobid_frontend#20]
@psg0796 
Reduce the height of yellow bar for coin status
![Screenshot_2020-04-27-14-29-49-130_com android chrome](https://user-images.githubusercontent.com/30129252/80353876-9f282600-8893-11ea-8091-c5f968acafe2.jpg)

**Comment by psg0796** [comment]
update done in commit id --> 101fd37f6a9d4a0956daa4a66f34996dcdf40082
