### ISSUE TITLE
Header and CoBid Logo height reduction

### ISSUE THREAD

**Issue by Raushantechfest** [IamAbhiKaushik/cobid_frontend#22]
![Screenshot_2020-04-27-14-31-27-379_com android chrome](https://user-images.githubusercontent.com/30129252/80354219-11990600-8894-11ea-9cbf-6c47db4f1ec8.jpg)

Reduce the size of CoBid and also of the purple bar height

**Comment by psg0796** [comment]
updated in commit id --> 67748aa90e7f3cf8eab8bb8172530d203b87fb34
