### ISSUE TITLE
Debug username

### ISSUE THREAD

**Issue by Raushantechfest** [IamAbhiKaushik/cobid_frontend#33]
![Screenshot_2020-04-30-12-12-34-265_com android chrome](https://user-images.githubusercontent.com/30129252/80680339-31226f80-8adc-11ea-879b-a5a1fb92ded0.jpg)

Hi username k jagah Hi name of the person

Example - replace : Hi raushan68 with "Hi Raushan"

**Comment by psg0796** [comment]
Check it once again and confirm
